### ISSUE TITLE
BTW, Gitter is not an option for me.  Site restricted.

### ISSUE THREAD

**Issue by RoyChapman** [githubteacher/developers-may-2016#133]
BTW, Gitter is not an option for me.  Site restricted.

**Comment by RoyChapman** [comment]
@githubteacher core.autolf true for Windows?  Even using GitBash?

**Comment by RoyChapman** [comment]
@githubteacher error
chapmar@W01B5HK3 ~/scratch
$ git clone https://github.com/githubteacher/developers-may-2016.git
Cloning into 'developers-may-2016'...
fatal: unable to access 'https://github.com/githubteacher/developers-may-2016.git/': Could not resolve host: github.com

Can't use gitter!

**Comment by hectorsector** [comment]
@RoyChapman the same issue that's causing you to be unable to access Gitter may be unable to access GitHub.com -- for this class we are using GitHub.com. Do you have proxy settings that you know of? If so, I can help you set them for `git`

**Comment by RoyChapman** [comment]
Access to Gitter is prevented because we are not allowed to use IM outside the bank.

I can access github.com from the browser, just not the command line

A bit late in the day now.  Oh well :-(

**Comment by hectorsector** [comment]
@RoyChapman no worries you'll get a video of the session, as well as the chat log will be posted to the class repository so you can always revisit what we did. Although you may be able to access github.com, the same firewall that's causing you to be unable to access Gitter may be causing issues with the clone command. Try cloning with SSH instead https://help.github.com/articles/which-remote-url-should-i-use/
