### ISSUE TITLE
@githubteacher cannot access gitter

### ISSUE THREAD

**Issue by aparentMMS** [githubteacher/developers-may-2016#140]
can't ask questions, can we use gotomeeting chat? 

trying to authorize with twitter nothing happens. I am logged in to twitter. this is my work github account and don't think they want to allow access.

**Comment by aparentMMS** [comment]
how to update git from 1.9.5

**Comment by kinjalin** [comment]
While cloning we have an error on Powershell 
Cloning into 'developers-may-2016'...
fatal: unable to access 'https://github.com/githubteacher/developers-may-2016.git/'  Could not resolve host: github.com

Is this something to do with our security restrictions

**Comment by hectorsector** [comment]
@aparentMMS it looks like you finally got access to Gitter so I am closing this Issue but feel free to reopen if you happen to be unable to get into Gitter.

**Comment by aparentMMS** [comment]
I gave in and used my github account, but the twitter link did not ever finish authenticating. A bug should be filed for that!

**Comment by hectorsector** [comment]
@aparentMMS bah sorry -- I've actually never tried logging in through Twitter only through GitHub auth. I'm glad that @brianamarie and you were able to work through some of the steps together though

**Comment by brianamarie** [comment]
> A bug should be filed for that!

@aparentMMS I agree! Gitter is open source, so I totally agree with opening an issue! https://github.com/gitterHQ
