### ISSUE TITLE
Unable to edit the url

### ISSUE THREAD

**Issue by Amandeep2930** [githubteacher/developers-may-2016#224]
getting the msg as Please enter the url : githubschool.github.io/github-games

**Comment by brianamarie** [comment]
@Amandeep2930 That's okay - it's broken on purpose so we can fix it together. 😄

**Comment by brianamarie** [comment]
@Amandeep2930 When you clone, make sure the URL includes your yoursername `git clone https://github.com/YOURUSERNAME/github-games.git` 👍

**Comment by brianamarie** [comment]
I am going to close this issue. Hopefully all is working well now! Please feel free to comment here again if you continue to have questions. :smile:

**Comment by brianamarie** [comment]
@Amandeep2930 Are you still having questions?

**Comment by Amandeep2930** [comment]
when i clone   git clone https://github.com/Amandeep2930/github-games.git

error:Cloning into 'github-games'...
fatal: unable to access 'https://github.com/Amandeep2930/github-games.git/': Could not resolve host: github.com

**Comment by brianamarie** [comment]
@Amandeep2930 Are you on the same computer where you cloned yesterday?

**Comment by Amandeep2930** [comment]
yes but i couldn't clone it yesterday as well it gives permission error .

**Comment by brianamarie** [comment]
@Amandeep2930 Ah, I see. I'm sorry to hear you couldn't clone yesterday, either. Have you given your GitHub login information through the command line?

**Comment by Amandeep2930** [comment]
i had set it through git config :username and email

**Comment by brianamarie** [comment]
@Amandeep2930 Okay. Are you perchance using a network with a firewall or specific proxy settings?

**Comment by Amandeep2930** [comment]
yes

**Comment by brianamarie** [comment]
@Amandeep2930 Okay.

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`
- change proxyuser to your proxy user
- change proxypwd to your proxy password
- change proxy.server.com to the URL of your proxy server
- change 8080 to the proxy port configured on your proxy server

If you decide at any time to reset this proxy and work without (no proxy):

Commands to use:

`git config --global --unset http.proxy`

Finally, to check the currently set proxy;

`git config --global --get http.proxy`

I found this [here](http://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server). Please let me know if this is helpful. 😄

**Comment by Amandeep2930** [comment]
I can try the steps n get in sync with Cynthia .Thankz Briana

**Comment by brianamarie** [comment]
I am going to close this issue. Hopefully all is working well now! Please feel free to comment here again if you continue to have questions. :smile:
